import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../utils/fetchInterceptor";
import CacheManager from "../components/CacheManager";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Spotify Vibe Generator",
  description: "Generated by Efe Katircioglu",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`} suppressHydrationWarning={true}>
        <CacheManager />
        {children}
      </body>
    </html>
  );
}
